curl_test.com c1_cp_cis-codif_h1_1d_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-codif_h1_1d_pef_yyyymmdd.xml
curl_test.com c1_cp_cis-codif_he1_1d_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-codif_he1_1d_pef_yyyymmdd.xml
curl_test.com c1_cp_cis-codif_hs_h1_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-codif_hs_h1_pef_yyyymmdd.xml
curl_test.com c1_cp_cis-codif_hs_h1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-codif_hs_h1_pf_yyyymmdd.xml
curl_test.com c1_cp_cis-codif_hs_h1_psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-codif_hs_h1_psd_yyyymmdd.xml
curl_test.com c1_cp_cis-codif_hs_he1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-codif_hs_he1_pf_yyyymmdd.xml
curl_test.com c1_cp_cis-codif_hs_he1_psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-codif_hs_he1_psd_yyyymmdd.xml
curl_test.com c1_cp_cis-codif_hs_o1_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-codif_hs_o1_pef_yyyymmdd.xml
curl_test.com c1_cp_cis-codif_hs_o1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-codif_hs_o1_pf_yyyymmdd.xml
curl_test.com c1_cp_cis-codif_hs_o1_psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-codif_hs_o1_psd_yyyymmdd.xml
curl_test.com c1_cp_cis-codif_o1_1d_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-codif_o1_1d_pef_yyyymmdd.xml
curl_test.com c1_cp_cis-codif_pad_hs_h1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-codif_pad_hs_h1_pf_yyyymmdd.xml
curl_test.com c1_cp_cis-codif_pad_hs_he1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-codif_pad_hs_he1_pf_yyyymmdd.xml
curl_test.com c1_cp_cis-codif_pad_hs_o1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-codif_pad_hs_o1_pf_yyyymmdd.xml
curl_test.com c1_cp_cis-hia_hs_1d_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-hia_hs_1d_pef_yyyymmdd.xml
curl_test.com c1_cp_cis-hia_hs_mag_ions_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-hia_hs_mag_ions_pef_yyyymmdd.xml
curl_test.com c1_cp_cis-hia_hs_mag_ions_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-hia_hs_mag_ions_pf_yyyymmdd.xml
curl_test.com c1_cp_cis-hia_hs_mag_ions_psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-hia_hs_mag_ions_psd_yyyymmdd.xml
curl_test.com c1_cp_cis-hia_hs_sw_ions_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-hia_hs_sw_ions_pef_yyyymmdd.xml
curl_test.com c1_cp_cis-hia_hs_sw_ions_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-hia_hs_sw_ions_pf_yyyymmdd.xml
curl_test.com c1_cp_cis-hia_hs_sw_ions_psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-hia_hs_sw_ions_psd_yyyymmdd.xml
curl_test.com c1_cp_cis-hia_ls_1d_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-hia_ls_1d_pef_yyyymmdd.xml
curl_test.com c1_cp_cis-hia_ls_sw_ions_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-hia_ls_sw_ions_pef_yyyymmdd.xml
curl_test.com c1_cp_cis-hia_ls_sw_ions_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-hia_ls_sw_ions_pf_yyyymmdd.xml
curl_test.com c1_cp_cis-hia_ls_sw_ions_psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-hia_ls_sw_ions_psd_yyyymmdd.xml
curl_test.com c1_cp_cis-hia_pad_hs_mag_ions_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_cis-hia_pad_hs_mag_ions_pf_yyyymmdd.xml
curl_test.com c1_cp_edi_aedc yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_edi_aedc_yyyymmdd.xml
curl_test.com c1_cp_edi_mp yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_edi_mp_yyyymmdd.xml
curl_test.com c1_cp_edi_qzc yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_edi_qzc_yyyymmdd.xml
curl_test.com c1_cp_edi_spin yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_edi_spin_yyyymmdd.xml
curl_test.com c1_cp_efw_l3_e3d_inert yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_efw_l3_e3d_inert_yyyymmdd.xml
curl_test.com c1_cp_efw_l3_p yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_efw_l3_p_yyyymmdd.xml
curl_test.com c1_cp_efw_l3_v3d_inert yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_efw_l3_v3d_inert_yyyymmdd.xml
curl_test.com c1_cp_fgm_5vps yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_fgm_5vps_yyyymmdd.xml
curl_test.com c1_cp_rap_e3dd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_rap_e3dd_yyyymmdd.xml
curl_test.com c1_cp_rap_espct6 yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_rap_espct6_yyyymmdd.xml
curl_test.com c1_cp_rap_hspct yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_rap_hspct_yyyymmdd.xml
curl_test.com c1_cp_rap_i3dm_cno yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_rap_i3dm_cno_yyyymmdd.xml
curl_test.com c1_cp_rap_i3dm_h yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_rap_i3dm_h_yyyymmdd.xml
curl_test.com c1_cp_rap_i3dm_he yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_rap_i3dm_he_yyyymmdd.xml
curl_test.com c1_cp_rap_ispct_cno yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_rap_ispct_cno_yyyymmdd.xml
curl_test.com c1_cp_rap_ispct_he yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_rap_ispct_he_yyyymmdd.xml
curl_test.com c1_cp_rap_l3dd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_rap_l3dd_yyyymmdd.xml
curl_test.com c1_cp_rap_pad_cno yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_rap_pad_cno_yyyymmdd.xml
curl_test.com c1_cp_rap_pad_e3dd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_rap_pad_e3dd_yyyymmdd.xml
curl_test.com c1_cp_rap_pad_h yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_rap_pad_h_yyyymmdd.xml
curl_test.com c1_cp_rap_pad_he yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_rap_pad_he_yyyymmdd.xml
curl_test.com c1_cp_rap_pad_l3dd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_rap_pad_l3dd_yyyymmdd.xml
curl_test.com c1_cp_sta_cwf_gse yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_sta_cwf_gse_yyyymmdd.xml
curl_test.com c1_cp_sta_ppp yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_sta_ppp_yyyymmdd.xml
curl_test.com c1_cp_sta_psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_sta_psd_yyyymmdd.xml
curl_test.com c1_cp_sta_sm yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_sta_sm_yyyymmdd.xml
curl_test.com c1_cp_whi_active yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_whi_active_yyyymmdd.xml
curl_test.com c1_cp_whi_electron_density yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_whi_electron_density_yyyymmdd.xml
curl_test.com c1_cp_whi_natural yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_whi_natural_yyyymmdd.xml
curl_test.com c1_cp_whi_passive_active yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_whi_passive_active_yyyymmdd.xml
curl_test.com c1_cp_whi_wave_form_energy yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c1_cp_whi_wave_form_energy_yyyymmdd.xml
curl_test.com c2_cp_edi_aedc yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_edi_aedc_yyyymmdd.xml
curl_test.com c2_cp_edi_mp yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_edi_mp_yyyymmdd.xml
curl_test.com c2_cp_edi_qzc yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_edi_qzc_yyyymmdd.xml
curl_test.com c2_cp_edi_spin yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_edi_spin_yyyymmdd.xml
curl_test.com c2_cp_efw_l3_e3d_inert yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_efw_l3_e3d_inert_yyyymmdd.xml
curl_test.com c2_cp_efw_l3_p yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_efw_l3_p_yyyymmdd.xml
curl_test.com c2_cp_efw_l3_v3d_inert yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_efw_l3_v3d_inert_yyyymmdd.xml
curl_test.com c2_cp_fgm_5vps yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_fgm_5vps_yyyymmdd.xml
curl_test.com c2_cp_rap_e3dd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_rap_e3dd_yyyymmdd.xml
curl_test.com c2_cp_rap_espct6 yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_rap_espct6_yyyymmdd.xml
curl_test.com c2_cp_rap_hspct yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_rap_hspct_yyyymmdd.xml
curl_test.com c2_cp_rap_i3dm_cno yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_rap_i3dm_cno_yyyymmdd.xml
curl_test.com c2_cp_rap_i3dm_h yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_rap_i3dm_h_yyyymmdd.xml
curl_test.com c2_cp_rap_i3dm_he yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_rap_i3dm_he_yyyymmdd.xml
curl_test.com c2_cp_rap_ispct_cno yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_rap_ispct_cno_yyyymmdd.xml
curl_test.com c2_cp_rap_ispct_he yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_rap_ispct_he_yyyymmdd.xml
curl_test.com c2_cp_rap_l3dd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_rap_l3dd_yyyymmdd.xml
curl_test.com c2_cp_rap_pad_e3dd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_rap_pad_e3dd_yyyymmdd.xml
curl_test.com c2_cp_rap_pad_h yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_rap_pad_h_yyyymmdd.xml
curl_test.com c2_cp_rap_pad_he yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_rap_pad_he_yyyymmdd.xml
curl_test.com c2_cp_rap_pad_l3dd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_rap_pad_l3dd_yyyymmdd.xml
curl_test.com c2_cp_sta_cwf_gse yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_sta_cwf_gse_yyyymmdd.xml
curl_test.com c2_cp_sta_ppp yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_sta_ppp_yyyymmdd.xml
curl_test.com c2_cp_sta_psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_sta_psd_yyyymmdd.xml
curl_test.com c2_cp_sta_sm yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_sta_sm_yyyymmdd.xml
curl_test.com c2_cp_whi_active yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_whi_active_yyyymmdd.xml
curl_test.com c2_cp_whi_electron_density yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_whi_electron_density_yyyymmdd.xml
curl_test.com c2_cp_whi_natural yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_whi_natural_yyyymmdd.xml
curl_test.com c2_cp_whi_passive_active yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_whi_passive_active_yyyymmdd.xml
curl_test.com c2_cp_whi_wave_form_energy yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c2_cp_whi_wave_form_energy_yyyymmdd.xml
curl_test.com c3_cp_cis-codif_h1_1d_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-codif_h1_1d_pef_yyyymmdd.xml
curl_test.com c3_cp_cis-codif_he1_1d_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-codif_he1_1d_pef_yyyymmdd.xml
curl_test.com c3_cp_cis-codif_hs_h1_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-codif_hs_h1_pef_yyyymmdd.xml
curl_test.com c3_cp_cis-codif_hs_h1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-codif_hs_h1_pf_yyyymmdd.xml
curl_test.com c3_cp_cis-codif_hs_h1_psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-codif_hs_h1_psd_yyyymmdd.xml
curl_test.com c3_cp_cis-codif_hs_he1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-codif_hs_he1_pf_yyyymmdd.xml
curl_test.com c3_cp_cis-codif_hs_he1_psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-codif_hs_he1_psd_yyyymmdd.xml
curl_test.com c3_cp_cis-codif_hs_o1_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-codif_hs_o1_pef_yyyymmdd.xml
curl_test.com c3_cp_cis-codif_hs_o1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-codif_hs_o1_pf_yyyymmdd.xml
curl_test.com c3_cp_cis-codif_hs_o1_psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-codif_hs_o1_psd_yyyymmdd.xml
curl_test.com c3_cp_cis-codif_o1_1d_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-codif_o1_1d_pef_yyyymmdd.xml
curl_test.com c3_cp_cis-codif_pad_hs_h1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-codif_pad_hs_h1_pf_yyyymmdd.xml
curl_test.com c3_cp_cis-codif_pad_hs_he1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-codif_pad_hs_he1_pf_yyyymmdd.xml
curl_test.com c3_cp_cis-codif_pad_hs_o1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-codif_pad_hs_o1_pf_yyyymmdd.xml
curl_test.com c3_cp_cis-hia_hs_1d_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-hia_hs_1d_pef_yyyymmdd.xml
curl_test.com c3_cp_cis-hia_hs_mag_ions_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-hia_hs_mag_ions_pef_yyyymmdd.xml
curl_test.com c3_cp_cis-hia_hs_mag_ions_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-hia_hs_mag_ions_pf_yyyymmdd.xml
curl_test.com c3_cp_cis-hia_hs_mag_ions_psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-hia_hs_mag_ions_psd_yyyymmdd.xml
curl_test.com c3_cp_cis-hia_hs_sw_ions_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-hia_hs_sw_ions_pef_yyyymmdd.xml
curl_test.com c3_cp_cis-hia_hs_sw_ions_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-hia_hs_sw_ions_pf_yyyymmdd.xml
curl_test.com c3_cp_cis-hia_hs_sw_ions_psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-hia_hs_sw_ions_psd_yyyymmdd.xml
curl_test.com c3_cp_cis-hia_ls_1d_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-hia_ls_1d_pef_yyyymmdd.xml
curl_test.com c3_cp_cis-hia_ls_sw_ions_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-hia_ls_sw_ions_pef_yyyymmdd.xml
curl_test.com c3_cp_cis-hia_ls_sw_ions_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-hia_ls_sw_ions_pf_yyyymmdd.xml
curl_test.com c3_cp_cis-hia_ls_sw_ions_psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-hia_ls_sw_ions_psd_yyyymmdd.xml
curl_test.com c3_cp_cis-hia_pad_hs_mag_ions_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_cis-hia_pad_hs_mag_ions_pf_yyyymmdd.xml
curl_test.com c3_cp_edi_aedc yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_edi_aedc_yyyymmdd.xml
curl_test.com c3_cp_edi_mp yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_edi_mp_yyyymmdd.xml
curl_test.com c3_cp_edi_qzc yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_edi_qzc_yyyymmdd.xml
curl_test.com c3_cp_edi_spin yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_edi_spin_yyyymmdd.xml
curl_test.com c3_cp_efw_l3_e3d_inert yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_efw_l3_e3d_inert_yyyymmdd.xml
curl_test.com c3_cp_efw_l3_p yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_efw_l3_p_yyyymmdd.xml
curl_test.com c3_cp_efw_l3_v3d_inert yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_efw_l3_v3d_inert_yyyymmdd.xml
curl_test.com c3_cp_fgm_5vps yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_fgm_5vps_yyyymmdd.xml
curl_test.com c3_cp_rap_e3dd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_rap_e3dd_yyyymmdd.xml
curl_test.com c3_cp_rap_espct6 yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_rap_espct6_yyyymmdd.xml
curl_test.com c3_cp_rap_hspct yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_rap_hspct_yyyymmdd.xml
curl_test.com c3_cp_rap_i3dm_cno yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_rap_i3dm_cno_yyyymmdd.xml
curl_test.com c3_cp_rap_i3dm_h yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_rap_i3dm_h_yyyymmdd.xml
curl_test.com c3_cp_rap_i3dm_he yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_rap_i3dm_he_yyyymmdd.xml
curl_test.com c3_cp_rap_ispct_cno yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_rap_ispct_cno_yyyymmdd.xml
curl_test.com c3_cp_rap_ispct_he yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_rap_ispct_he_yyyymmdd.xml
curl_test.com c3_cp_rap_l3dd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_rap_l3dd_yyyymmdd.xml
curl_test.com c3_cp_rap_pad_cno yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_rap_pad_cno_yyyymmdd.xml
curl_test.com c3_cp_rap_pad_e3dd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_rap_pad_e3dd_yyyymmdd.xml
curl_test.com c3_cp_rap_pad_h yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_rap_pad_h_yyyymmdd.xml
curl_test.com c3_cp_rap_pad_he yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_rap_pad_he_yyyymmdd.xml
curl_test.com c3_cp_rap_pad_l3dd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_rap_pad_l3dd_yyyymmdd.xml
curl_test.com c3_cp_sta_cwf_gse yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_sta_cwf_gse_yyyymmdd.xml
curl_test.com c3_cp_sta_ppp yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_sta_ppp_yyyymmdd.xml
curl_test.com c3_cp_sta_psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_sta_psd_yyyymmdd.xml
curl_test.com c3_cp_sta_sm yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_sta_sm_yyyymmdd.xml
curl_test.com c3_cp_whi_active yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_whi_active_yyyymmdd.xml
curl_test.com c3_cp_whi_electron_density yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_whi_electron_density_yyyymmdd.xml
curl_test.com c3_cp_whi_natural yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_whi_natural_yyyymmdd.xml
curl_test.com c3_cp_whi_passive_active yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_whi_passive_active_yyyymmdd.xml
curl_test.com c3_cp_whi_wave_form_energy yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c3_cp_whi_wave_form_energy_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_h1_1d_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_h1_1d_pef_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_he1_1d_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_he1_1d_pef_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_he1_density_corrected yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_he1_density_corrected_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_hs_h1_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_hs_h1_pef_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_hs_h1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_hs_h1_pf_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_hs_h1_psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_hs_h1_psd_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_hs_he1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_hs_he1_pf_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_hs_he1_psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_hs_he1_psd_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_hs_o1_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_hs_o1_pef_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_hs_o1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_hs_o1_pf_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_hs_o1_psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_hs_o1_psd_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_ls_h1_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_ls_h1_pef_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_ls_h1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_ls_h1_pf_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_ls_h1_psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_ls_h1_psd_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_ls_he1_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_ls_he1_pef_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_ls_he1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_ls_he1_pf_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_ls_o1_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_ls_o1_pef_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_ls_o1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_ls_o1_pf_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_ls_o1_psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_ls_o1_psd_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_o1_1d_pef yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_o1_1d_pef_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_pad_hs_h1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_pad_hs_h1_pf_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_pad_hs_he1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_pad_hs_he1_pf_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_pad_hs_o1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_pad_hs_o1_pf_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_pad_ls_h1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_pad_ls_h1_pf_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_pad_ls_he1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_pad_ls_he1_pf_yyyymmdd.xml
curl_test.com c4_cp_cis-codif_pad_ls_o1_pf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_cis-codif_pad_ls_o1_pf_yyyymmdd.xml
curl_test.com c4_cp_efw_l3_e3d_inert yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_efw_l3_e3d_inert_yyyymmdd.xml
curl_test.com c4_cp_efw_l3_p yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_efw_l3_p_yyyymmdd.xml
curl_test.com c4_cp_efw_l3_v3d_inert yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_efw_l3_v3d_inert_yyyymmdd.xml
curl_test.com c4_cp_fgm_5vps yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_fgm_5vps_yyyymmdd.xml
curl_test.com c4_cp_rap_e3dd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_rap_e3dd_yyyymmdd.xml
curl_test.com c4_cp_rap_espct6 yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_rap_espct6_yyyymmdd.xml
curl_test.com c4_cp_rap_hspct yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_rap_hspct_yyyymmdd.xml
curl_test.com c4_cp_rap_i3dm_cno yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_rap_i3dm_cno_yyyymmdd.xml
curl_test.com c4_cp_rap_i3dm_h yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_rap_i3dm_h_yyyymmdd.xml
curl_test.com c4_cp_rap_i3dm_he yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_rap_i3dm_he_yyyymmdd.xml
curl_test.com c4_cp_rap_ispct_cno yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_rap_ispct_cno_yyyymmdd.xml
curl_test.com c4_cp_rap_ispct_he yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_rap_ispct_he_yyyymmdd.xml
curl_test.com c4_cp_rap_l3dd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_rap_l3dd_yyyymmdd.xml
curl_test.com c4_cp_rap_pad_cno yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_rap_pad_cno_yyyymmdd.xml
curl_test.com c4_cp_rap_pad_e3dd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_rap_pad_e3dd_yyyymmdd.xml
curl_test.com c4_cp_rap_pad_h yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_rap_pad_h_yyyymmdd.xml
curl_test.com c4_cp_rap_pad_he yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_rap_pad_he_yyyymmdd.xml
curl_test.com c4_cp_rap_pad_l3dd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_rap_pad_l3dd_yyyymmdd.xml
curl_test.com c4_cp_sta_cwf_gse yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_sta_cwf_gse_yyyymmdd.xml
curl_test.com c4_cp_sta_ppp yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_sta_ppp_yyyymmdd.xml
curl_test.com c4_cp_sta_psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_sta_psd_yyyymmdd.xml
curl_test.com c4_cp_sta_sm yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_sta_sm_yyyymmdd.xml
curl_test.com c4_cp_whi_active yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_whi_active_yyyymmdd.xml
curl_test.com c4_cp_whi_electron_density yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_whi_electron_density_yyyymmdd.xml
curl_test.com c4_cp_whi_natural yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_whi_natural_yyyymmdd.xml
curl_test.com c4_cp_whi_passive_active yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_whi_passive_active_yyyymmdd.xml
curl_test.com c4_cp_whi_wave_form_energy yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_c4_cp_whi_wave_form_energy_yyyymmdd.xml
