curl -sS --request PUT --url https://api.datacite.org/dois/10.48322%2F541v-1f57 --user 'testorg.heliophy:6yard$TACK27' --header 'content-type: application/vnd.api+json' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_mms1_aspoc_srvy_l2.json
curl -sS --request PUT --url https://api.datacite.org/dois/10.48322%2F541v-1f57 --user 'testorg.heliophy:6yard$TACK27' --header 'content-type: application/vnd.api+json' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_mms1_aspoc_srvy_l2.json
curl -sS --request PUT --url https://api.datacite.org/dois/10.48322%2F541v-1f57 --user 'testorg.heliophy:6yard$TACK27' --header 'content-type: application/vnd.api+json' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_mms1_aspoc_srvy_l2.json
curl -sS --request PUT --url https://api.datacite.org/dois/10.48322%2F541v-1f57 --user 'testorg.heliophy:6yard$TACK27' --header 'content-type: application/vnd.api+json' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_mms1_aspoc_srvy_l2.json
curl -sS --request PUT --url https://api.datacite.org/dois/10.48322%2F541v-1f57 --user 'testorg.heliophy:6yard$TACK27' --header 'content-type: application/vnd.api+json' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_mms1_aspoc_srvy_l2.json
curl -sS --request PUT --url https://api.datacite.org/dois/10.48322%2F541v-1f57 --user 'testorg.heliophy:6yard$TACK27' --header 'content-type: application/vnd.api+json' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_mms1_aspoc_srvy_l2.json
curl -sS --request PUT --url https://api.datacite.org/dois/10.48322%2F541v-1f57 --user 'testorg.heliophy:6yard$TACK27' --header 'content-type: application/vnd.api+json' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_mms1_aspoc_srvy_l2.json
curl -sS --request PUT --url https://api.datacite.org/dois/10.48322%2F541v-1f57 --user 'testorg.heliophy:6yard$TACK27' --header 'content-type: application/vnd.api+json' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_mms1_aspoc_srvy_l2.json
curl -sS --request PUT --url https://api.datacite.org/dois/10.48322%2F541v-1f57 --user 'testorg.heliophy:6yard$TACK27' --header 'content-type: application/vnd.api+json' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_mms1_aspoc_srvy_l2.json
curl -sS --request PUT --url https://api.datacite.org/dois/10.48322%2F541v-1f57 --user 'testorg.heliophy:6yard$TACK27' --header 'content-type: application/vnd.api+json' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_mms1_aspoc_srvy_l2.json
curl -sS --request PUT --url https://api.datacite.org/dois/10.48322%2F541v-1f57 --user 'testorg.heliophy:6yard$TACK27' --header 'content-type: application/vnd.api+json' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_mms1_aspoc_srvy_l2.json
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_lanl89.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_lanl89.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_lanl89.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_lanl89.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
curl -sSX POST -H 'Content-Type: application/vnd.api+json' -u 'testorg.heliophy:6yard$TACK27' -d @TEST_DATACITE/JSON/MMS/datacite_json_doi_template_a1_k0_mpa.json https://api.test.datacite.org/dois
