curl -ksSX POST -H 'Content-Type: application/vnd.api+json' -u 'heliophy.spdf:Tranquillity$Base&Eagle' -d @DATACITE/JSON/IMAGE/datacite_json_doi_template_im_electron_density_rpi.json https://api.datacite.org/dois
curl -ksSX POST -H 'Content-Type: application/vnd.api+json' -u 'heliophy.spdf:Tranquillity$Base&Eagle' -d @DATACITE/JSON/IMAGE/datacite_json_doi_template_im_hk_ads im_hk_ast im_hk_com im_hk_fsw im_hk_pwr im_hk_tml.json https://api.datacite.org/dois
curl -ksSX POST -H 'Content-Type: application/vnd.api+json' -u 'heliophy.spdf:Tranquillity$Base&Eagle' -d @DATACITE/JSON/IMAGE/datacite_json_doi_template_im_hk_ads im_hk_ast im_hk_com im_hk_fsw im_hk_pwr im_hk_tml.json https://api.datacite.org/dois
curl -ksSX POST -H 'Content-Type: application/vnd.api+json' -u 'heliophy.spdf:Tranquillity$Base&Eagle' -d @DATACITE/JSON/IMAGE/datacite_json_doi_template_im_hk_ads im_hk_ast im_hk_com im_hk_fsw im_hk_pwr im_hk_tml.json https://api.datacite.org/dois
curl -ksSX POST -H 'Content-Type: application/vnd.api+json' -u 'heliophy.spdf:Tranquillity$Base&Eagle' -d @DATACITE/JSON/IMAGE/datacite_json_doi_template_im_hk_ads im_hk_ast im_hk_com im_hk_fsw im_hk_pwr im_hk_tml.json https://api.datacite.org/dois
curl -ksSX POST -H 'Content-Type: application/vnd.api+json' -u 'heliophy.spdf:Tranquillity$Base&Eagle' -d @DATACITE/JSON/IMAGE/datacite_json_doi_template_im_hk_ads im_hk_ast im_hk_com im_hk_fsw im_hk_pwr im_hk_tml.json https://api.datacite.org/dois
curl -ksSX POST -H 'Content-Type: application/vnd.api+json' -u 'heliophy.spdf:Tranquillity$Base&Eagle' -d @DATACITE/JSON/IMAGE/datacite_json_doi_template_im_hk_ads im_hk_ast im_hk_com im_hk_fsw im_hk_pwr im_hk_tml.json https://api.datacite.org/dois
curl -ksSX POST -H 'Content-Type: application/vnd.api+json' -u 'heliophy.spdf:Tranquillity$Base&Eagle' -d @DATACITE/JSON/IMAGE/datacite_json_doi_template_im_k0_euv.json https://api.datacite.org/dois
curl -ksSX POST -H 'Content-Type: application/vnd.api+json' -u 'heliophy.spdf:Tranquillity$Base&Eagle' -d @DATACITE/JSON/IMAGE/datacite_json_doi_template_im_k0_hena.json https://api.datacite.org/dois
curl -ksSX POST -H 'Content-Type: application/vnd.api+json' -u 'heliophy.spdf:Tranquillity$Base&Eagle' -d @DATACITE/JSON/IMAGE/datacite_json_doi_template_im_k0_lena.json https://api.datacite.org/dois
curl -ksSX POST -H 'Content-Type: application/vnd.api+json' -u 'heliophy.spdf:Tranquillity$Base&Eagle' -d @DATACITE/JSON/IMAGE/datacite_json_doi_template_im_k0_mena.json https://api.datacite.org/dois
curl -ksSX POST -H 'Content-Type: application/vnd.api+json' -u 'heliophy.spdf:Tranquillity$Base&Eagle' -d @DATACITE/JSON/IMAGE/datacite_json_doi_template_im_k0_rpi.json https://api.datacite.org/dois
curl -ksSX POST -H 'Content-Type: application/vnd.api+json' -u 'heliophy.spdf:Tranquillity$Base&Eagle' -d @DATACITE/JSON/IMAGE/datacite_json_doi_template_im_k0_sie.json https://api.datacite.org/dois
curl -ksSX POST -H 'Content-Type: application/vnd.api+json' -u 'heliophy.spdf:Tranquillity$Base&Eagle' -d @DATACITE/JSON/IMAGE/datacite_json_doi_template_im_k0_sip.json https://api.datacite.org/dois
curl -ksSX POST -H 'Content-Type: application/vnd.api+json' -u 'heliophy.spdf:Tranquillity$Base&Eagle' -d @DATACITE/JSON/IMAGE/datacite_json_doi_template_im_k0_wic.json https://api.datacite.org/dois
curl -ksSX POST -H 'Content-Type: application/vnd.api+json' -u 'heliophy.spdf:Tranquillity$Base&Eagle' -d @DATACITE/JSON/IMAGE/datacite_json_doi_template_im_or_pre.json https://api.datacite.org/dois
