curl_test.com solo_l2_epd-ept-asun-burst-ele-close yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-ept-asun-burst-ele-close_yyyymmdd.xml
curl_test.com solo_l2_epd-ept-asun-burst-ion yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-ept-asun-burst-ion_yyyymmdd.xml
curl_test.com solo_l2_epd-ept-asun-hcad yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-ept-asun-hcad_yyyymmdd.xml
curl_test.com solo_l2_epd-ept-asun-rates yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-ept-asun-rates_yyyymmdd.xml
curl_test.com solo_l2_epd-ept-north-burst-ele-close yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-ept-north-burst-ele-close_yyyymmdd.xml
curl_test.com solo_l2_epd-ept-north-burst-ion yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-ept-north-burst-ion_yyyymmdd.xml
curl_test.com solo_l2_epd-ept-north-hcad yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-ept-north-hcad_yyyymmdd.xml
curl_test.com solo_l2_epd-ept-north-rates yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-ept-north-rates_yyyymmdd.xml
curl_test.com solo_l2_epd-ept-south-burst-ele-close yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-ept-south-burst-ele-close_yyyymmdd.xml
curl_test.com solo_l2_epd-ept-south-burst-ion yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-ept-south-burst-ion_yyyymmdd.xml
curl_test.com solo_l2_epd-ept-south-hcad yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-ept-south-hcad_yyyymmdd.xml
curl_test.com solo_l2_epd-ept-south-rates yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-ept-south-rates_yyyymmdd.xml
curl_test.com solo_l2_epd-ept-sun-burst-ele-close yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-ept-sun-burst-ele-close_yyyymmdd.xml
curl_test.com solo_l2_epd-ept-sun-burst-ion yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-ept-sun-burst-ion_yyyymmdd.xml
curl_test.com solo_l2_epd-ept-sun-hcad yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-ept-sun-hcad_yyyymmdd.xml
curl_test.com solo_l2_epd-ept-sun-rates yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-ept-sun-rates_yyyymmdd.xml
curl_test.com solo_l2_epd-het-asun-burst yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-het-asun-burst_yyyymmdd.xml
curl_test.com solo_l2_epd-het-asun-rates yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-het-asun-rates_yyyymmdd.xml
curl_test.com solo_l2_epd-het-north-burst yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-het-north-burst_yyyymmdd.xml
curl_test.com solo_l2_epd-het-north-rates yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-het-north-rates_yyyymmdd.xml
curl_test.com solo_l2_epd-het-south-burst yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-het-south-burst_yyyymmdd.xml
curl_test.com solo_l2_epd-het-south-rates yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-het-south-rates_yyyymmdd.xml
curl_test.com solo_l2_epd-het-sun-burst yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-het-sun-burst_yyyymmdd.xml
curl_test.com solo_l2_epd-het-sun-rates yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-het-sun-rates_yyyymmdd.xml
curl_test.com solo_l2_epd-sis-a-hehist yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-sis-a-hehist_yyyymmdd.xml
curl_test.com solo_l2_epd-sis-a-rates-fast yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-sis-a-rates-fast_yyyymmdd.xml
curl_test.com solo_l2_epd-sis-a-rates-medium yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-sis-a-rates-medium_yyyymmdd.xml
curl_test.com solo_l2_epd-sis-a-rates-slow yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-sis-a-rates-slow_yyyymmdd.xml
curl_test.com solo_l2_epd-sis-b-hehist yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-sis-b-hehist_yyyymmdd.xml
curl_test.com solo_l2_epd-sis-b-rates-fast yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-sis-b-rates-fast_yyyymmdd.xml
curl_test.com solo_l2_epd-sis-b-rates-medium yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-sis-b-rates-medium_yyyymmdd.xml
curl_test.com solo_l2_epd-sis-b-rates-slow yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-sis-b-rates-slow_yyyymmdd.xml
curl_test.com solo_l2_epd-step-burst yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-step-burst_yyyymmdd.xml
curl_test.com solo_l2_epd-step-hcad yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-step-hcad_yyyymmdd.xml
curl_test.com solo_l2_epd-step-main yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-step-main_yyyymmdd.xml
curl_test.com solo_l2_epd-step-rates yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_epd-step-rates_yyyymmdd.xml
curl_test.com solo_l2_mag-rtn-burst yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_mag-rtn-burst_yyyymmdd.xml
curl_test.com solo_l2_mag-rtn-ll yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_mag-rtn-ll_yyyymmdd.xml
curl_test.com solo_l2_mag-rtn-ll-1-minute yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_mag-rtn-ll-1-minute_yyyymmdd.xml
curl_test.com solo_l2_mag-rtn-normal yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_mag-rtn-normal_yyyymmdd.xml
curl_test.com solo_l2_mag-rtn-normal-1-minute yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_mag-rtn-normal-1-minute_yyyymmdd.xml
curl_test.com solo_l2_mag-srf-burst yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_mag-srf-burst_yyyymmdd.xml
curl_test.com solo_l2_mag-srf-ll yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_mag-srf-ll_yyyymmdd.xml
curl_test.com solo_l2_mag-srf-normal yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_mag-srf-normal_yyyymmdd.xml
curl_test.com solo_l2_mag-vso-burst yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_mag-vso-burst_yyyymmdd.xml
curl_test.com solo_l2_mag-vso-normal yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_mag-vso-normal_yyyymmdd.xml
curl_test.com solo_l2_mag-vso-normal-1-minute yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_mag-vso-normal-1-minute_yyyymmdd.xml
curl_test.com solo_l2_rpw-hfr-surv yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_rpw-hfr-surv_yyyymmdd.xml
curl_test.com solo_l2_rpw-lfr-surv-asm yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_rpw-lfr-surv-asm_yyyymmdd.xml
curl_test.com solo_l2_rpw-lfr-surv-bp1 yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_rpw-lfr-surv-bp1_yyyymmdd.xml
curl_test.com solo_l2_rpw-lfr-surv-bp2 yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_rpw-lfr-surv-bp2_yyyymmdd.xml
curl_test.com solo_l2_rpw-lfr-surv-cwf-b yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_rpw-lfr-surv-cwf-b_yyyymmdd.xml
curl_test.com solo_l2_rpw-lfr-surv-cwf-e yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_rpw-lfr-surv-cwf-e_yyyymmdd.xml
curl_test.com solo_l2_rpw-tds-surv-hist1d yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_rpw-tds-surv-hist1d_yyyymmdd.xml
curl_test.com solo_l2_rpw-tds-surv-hist2d yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_rpw-tds-surv-hist2d_yyyymmdd.xml
curl_test.com solo_l2_rpw-tds-surv-stat yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_rpw-tds-surv-stat_yyyymmdd.xml
curl_test.com solo_l2_swa-eas-pad-def yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_swa-eas-pad-def_yyyymmdd.xml
curl_test.com solo_l2_swa-eas-pad-dnf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_swa-eas-pad-dnf_yyyymmdd.xml
curl_test.com solo_l2_swa-eas1-nm3d-def yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_swa-eas1-nm3d-def_yyyymmdd.xml
curl_test.com solo_l2_swa-eas1-nm3d-dnf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_swa-eas1-nm3d-dnf_yyyymmdd.xml
curl_test.com solo_l2_swa-eas1-nm3d-psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_swa-eas1-nm3d-psd_yyyymmdd.xml
curl_test.com solo_l2_swa-eas1-ss-def yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_swa-eas1-ss-def_yyyymmdd.xml
curl_test.com solo_l2_swa-eas1-ss-dnf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_swa-eas1-ss-dnf_yyyymmdd.xml
curl_test.com solo_l2_swa-eas1-ss-psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_swa-eas1-ss-psd_yyyymmdd.xml
curl_test.com solo_l2_swa-eas2-nm3d-def yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_swa-eas2-nm3d-def_yyyymmdd.xml
curl_test.com solo_l2_swa-eas2-nm3d-dnf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_swa-eas2-nm3d-dnf_yyyymmdd.xml
curl_test.com solo_l2_swa-eas2-nm3d-psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_swa-eas2-nm3d-psd_yyyymmdd.xml
curl_test.com solo_l2_swa-eas2-ss-def yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_swa-eas2-ss-def_yyyymmdd.xml
curl_test.com solo_l2_swa-eas2-ss-dnf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_swa-eas2-ss-dnf_yyyymmdd.xml
curl_test.com solo_l2_swa-eas2-ss-psd yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_swa-eas2-ss-psd_yyyymmdd.xml
curl_test.com solo_l2_swa-his-rates yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_swa-his-rates_yyyymmdd.xml
curl_test.com solo_l2_swa-pas-eflux yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_swa-pas-eflux_yyyymmdd.xml
curl_test.com solo_l2_swa-pas-grnd-mom yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_swa-pas-grnd-mom_yyyymmdd.xml
curl_test.com solo_l2_swa-pas-vdf yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l2_swa-pas-vdf_yyyymmdd.xml
curl_test.com solo_l3_rpw-bia-density yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l3_rpw-bia-density_yyyymmdd.xml
curl_test.com solo_l3_rpw-bia-density-10-seconds yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l3_rpw-bia-density-10-seconds_yyyymmdd.xml
curl_test.com solo_l3_rpw-bia-efield yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l3_rpw-bia-efield_yyyymmdd.xml
curl_test.com solo_l3_rpw-bia-efield-10-seconds yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l3_rpw-bia-efield-10-seconds_yyyymmdd.xml
curl_test.com solo_l3_rpw-bia-scpot yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l3_rpw-bia-scpot_yyyymmdd.xml
curl_test.com solo_l3_rpw-bia-scpot-10-seconds yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l3_rpw-bia-scpot-10-seconds_yyyymmdd.xml
curl_test.com solo_l3_swa-his-comp-10min yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_l3_swa-his-comp-10min_yyyymmdd.xml
curl_test.com solo_ll02_epd-ept-asun-rates yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_ll02_epd-ept-asun-rates_yyyymmdd.xml
curl_test.com solo_ll02_epd-ept-north-rates yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_ll02_epd-ept-north-rates_yyyymmdd.xml
curl_test.com solo_ll02_epd-ept-south-rates yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_ll02_epd-ept-south-rates_yyyymmdd.xml
curl_test.com solo_ll02_epd-ept-sun-rates yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_ll02_epd-ept-sun-rates_yyyymmdd.xml
curl_test.com solo_ll02_epd-het-asun-rates yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_ll02_epd-het-asun-rates_yyyymmdd.xml
curl_test.com solo_ll02_epd-het-north-rates yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_ll02_epd-het-north-rates_yyyymmdd.xml
curl_test.com solo_ll02_epd-het-south-rates yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_ll02_epd-het-south-rates_yyyymmdd.xml
curl_test.com solo_ll02_epd-het-sun-rates yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_ll02_epd-het-sun-rates_yyyymmdd.xml
curl_test.com solo_ll02_epd-sis-a-rates yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_ll02_epd-sis-a-rates_yyyymmdd.xml
curl_test.com solo_ll02_epd-sis-b-rates yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_ll02_epd-sis-b-rates_yyyymmdd.xml
curl_test.com solo_ll02_epd-step-rates yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_ll02_epd-step-rates_yyyymmdd.xml
curl_test.com solo_ll02_mag yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_ll02_mag_yyyymmdd.xml
curl_test.com solo_ll02_rpw-sbm1 yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_ll02_rpw-sbm1_yyyymmdd.xml
curl_test.com solo_ll02_rpw-sbm2 yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_ll02_rpw-sbm2_yyyymmdd.xml
curl_test.com solo_ll02_rpw-tnr yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_ll02_rpw-tnr_yyyymmdd.xml
curl_test.com solo_ll02_swa-eas-ss yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_ll02_swa-eas-ss_yyyymmdd.xml
curl_test.com solo_ll02_swa-his-rat yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_ll02_swa-his-rat_yyyymmdd.xml
curl_test.com solo_ll02_swa-pas-mom yyyymmdd /home/jovyan/efs/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_solo_ll02_swa-pas-mom_yyyymmdd.xml
